sylius_user:
    resources:
        demo:
            user:
                classes:
                    model: Phpmob\DemoBundle\Model\DemoUser
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
