sylius_user:
    resources:
        demo:
            user:
                classes:
                    model: Cool\DemoBundle\Model\DemoUser
                    form: Cool\DemoBundle\Form\Type\DemoUserType
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
