phpmob_changmin:
    resource: "@ChangMinX/Resources/config/routing.xml"
    prefix:   /

phpmob_demo_admin:
    resource: "@PhpmobDemoBundle/Resources/config/routing/admin/main.yml"
    prefix: /admin
