file:
    resource: "@FileBundle/Resources/config/routing.xml"
    prefix:   /

phpmob_changmin:
    resource: "@ChangMin/Resources/config/routing.xml"
    prefix:   /admin

phpmob_demo_admin:
    resource: "@PhpmobDemoBundle/Resources/config/routing/admin/main.yml"
    prefix: /admin
