imports:
    #- { resource: "@PhpmobCmsBundle/Resources/config/app/phpmob_file.yml" }
    - { resource: "@PhpmobCmsBundle/Resources/config/app/sylius_resource.yml" }
    #- { resource: "@PhpmobCmsBundle/Resources/config/app/sylius_fixtures.yml" }
    - { resource: "@PhpmobCmsBundle/Resources/config/grids/admin/main.yml" }
