sylius_resource:
    resources:
        phpmob.page:
            classes:
                model: Phpmob\CmsBundle\Model\Page
                interface: Phpmob\CmsBundle\Model\PageInterface
                form: Phpmob\CmsBundle\Form\Type\PageType
            translation:
                classes:
                    model: Phpmob\CmsBundle\Model\PageTranslation
                    interface: Phpmob\CmsBundle\Model\PageTranslationInterface
                    form: Phpmob\CmsBundle\Form\Type\PageTranslationType
