services:
    demo.fixture.factory.demo_user:
        class: Phpmob\DemoBundle\Fixture\DemoUserFactory
        arguments:
            - "@sylius.factory.demo_user"

    demo.fixture.user:
        class: Phpmob\DemoBundle\Fixture\DemoUserFixture
        arguments:
            - "@sylius.manager.demo_user"
            - "@demo.fixture.factory.demo_user"
        tags:
            - { name: sylius_fixtures.fixture }
