sylius_admin_demo_user:
    resource: |
        alias: phpmob.page
        section: admin
        templates: ChangMin:Crud
        grid: phpmob_admin_page
        permission: true
        vars:
            all:
                templates:
                    form: PhpmobCmsBundle:Admin/Page:_form.html.twig
            index:
                icon: licon licon-note
                header: "Pages"
            create:
                header: "Create Page"
                breadcrumb:
                    index:
                        icon: licon licon-note
                        label: "Pages"
            update:
                header: "Edit Page"
                breadcrumb:
                    index:
                        icon: licon licon-note
                        label: "Pages"
            show:
                icon: icon icon-newspaper
                header: "See"
                breadcrumb:
                    index:
                        icon: licon licon-note
                        label: "Pages"
    type: sylius.resource
