sylius_admin_demo_user:
    resource: |
        alias: sylius.demo_user
        section: admin
        path: users
        templates: ChangMinX:Crud
        except: ['show']
        redirect: index
        grid: demo_admin_demo_user
        permission: true
        vars:
            all:
                templates:
                    form: PhpmobDemoBundle:DemoUser:_form.html.twig
            index:
                icon: icon icon-user
                header: "Demo Users"
    type: sylius.resource
