sylius_admin_demo_user:
    resource: |
        alias: sylius.demo_user
        section: admin
        path: users
        templates: Changmin:Crud
        except: ['show']
        redirect: index
        grid: sylius_admin_demo_user
        permission: true
        vars:
            all:
                templates:
                    form: PhpmobDemoBundle:DemoUser:_form.html.twig
            index:
                icon: lock
    type: sylius.resource
