PhpMob\DemoBundle\Model\DemoUser:
    type: mappedSuperclass
    table: demo_user

    oneToOne:
        image:
            targetEntity: PhpMob\DemoBundle\Model\DemoUserPictureInterface
            mappedBy: owner
            cascade: [ all ]

    oneToMany:
        images:
            targetEntity: PhpMob\DemoBundle\Model\DemoUserPictureInterface
            mappedBy: user
            orphanRemoval: true
            cascade: [ all ]
