Phpmob\DemoBundle\Model\DemoUserPicture:
    type: mappedSuperclass
    table: demo_user_picture

    oneToOne:
        owner:
            targetEntity: Sylius\Component\User\Model\UserInterface
            inversedBy: image
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: true
                #onDelete: CASCADE
