services:
    demo.fixture.factory.demo_user:
        class: Cool\DemoBundle\Fixture\DemoUserFactory
        arguments:
            - "@sylius.factory.demo_user"

    demo.fixture.demo_user:
        class: Cool\DemoBundle\Fixture\DemoUserFixture
        arguments:
            - "@sylius.manager.demo_user"
            - "@demo.fixture.factory.demo_user"
        tags:
            - { name: sylius_fixtures.fixture }

    demo.form.demo_user:
        class: Cool\DemoBundle\Form\Type\DemoUserType
        arguments:
            - "%sylius.model.demo_user.class%"
            - [ "sylius" ]
        tags:
            - { name: form.type }

    demo.form.demo_user_picture:
        class: Cool\DemoBundle\Form\Type\DemoUserPictureType
        arguments:
            - "%demo.model.user_picture.class%"
            - [ "sylius" ]
        tags:
            - { name: form.type }
